package me.justsid.mcservergui;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;

public final class EulaManager {

    public boolean isAccepted(Path serverDir) {
        Path eulaFile = serverDir.resolve(Constants.EULA_FILE);
        if (!Files.exists(eulaFile)) {
            return false;
        }

        try {
            return Files.readString(eulaFile).contains("eula=true");
        } catch (IOException e) {
            return false;
        }
    }

    public void accept(Path serverDir) throws IOException {
        Files.createDirectories(serverDir);
        Path eulaFile = serverDir.resolve(Constants.EULA_FILE);
        Files.writeString(
            eulaFile,
            "# Generated by McServerGUI\n" + "eula=true\n",
            StandardCharsets.UTF_8,
            StandardOpenOption.CREATE,
            StandardOpenOption.TRUNCATE_EXISTING
        );
    }
}